[pytest]
addopts = -v -s --html=reports/report.html --self-contained-html

pytest_html_report_title = TalentoLab - Resumen de ejecución
pytest_html_report_description = Suite UI + API completa

markers =
    ui: Tests de UI
    smoke: Tests críticos que deben funcionar siempre
    regresion: Suite completa de regresión
    api: Tests de API

python_functions = test_*
python_files = test_*.py
testpaths = tests tests_api